language: node_js
node_js:
  - "6"
  - "5"
  - "4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: yarn run lint
    - stage: test
      script: yarn run test:unit
    - script: yarn run test:e2e
